#! /bin/sh

### BEGIN INIT INFO
# Provides:		iosusb
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6	
# Short-Description:	ios usb infection daemon
### END INIT INFO

. /lib/lsb/init-functions

set -e

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	log_daemon_msg "Starting ios usb infection server" "iosusb" || true
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/ios-install.pid --exec /usr/bin/iosusb; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping ios usb infection server" "iosusb" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/ios-install.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  reload|force-reload)
	log_daemon_msg "Reloading ios usb infection server" "iosusb" || true
	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /var/run/ios-install.pid --exec /usr/bin/iosusb; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	log_daemon_msg "Restarting ios usb infection server" "iosusb" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/ios-install.pid
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/ios-install.pid --exec /usr/sbin/iosusb; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  try-restart)
	log_daemon_msg "Restarting ios usb infection server" "iosusb" || true
	RET=0
	start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/ios-install.pid || RET="$?"
	case $RET in
	    0)
		# old daemon stopped
		if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/ios-install.pid --exec /usr/bin/iosusb; then
		    log_end_msg 0 || true
		else
		    log_end_msg 1 || true
		fi
		;;
	    1)
		# daemon not running
		log_progress_msg "(not running)" || true
		log_end_msg 0 || true
		;;
	    *)
		# failed to stop
		log_progress_msg "(failed to stop)" || true
		log_end_msg 1 || true
		;;
	esac
	;;

  status)
	status_of_proc -p /var/run/ios-install.pid /usr/sbin/iosusb iosusb && exit 0 || exit $?
	;;

  *)
	log_daemon_msg "Usage: /etc/init.d/ios-install {start|stop|reload|force-reload|restart|try-restart|status}" || true
	exit 1
esac

exit 0
